# Generated by Django 5.0.6 on 2024-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=20)),
                ("sensor_1", models.CharField(max_length=20)),
                ("sensor_2", models.CharField(max_length=20)),
                ("sensor_3", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "devices",
            },
        ),
    ]
