# Generated by Django 5.0.6 on 2024-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="device",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
